In [54]:
# importando as bibliotecas necessárias

import pandas as pd
import numpy as np

In [2]:
# importando os dados

vendas = pd.read_csv("halloween_vendas.csv", encoding="utf-8", sep=",")

In [3]:
# mostrando as primeiras 3 linhas do dataframe

vendas.head(3)

,pedido_id,data_venda,produto,categoria,canal_venda,cidade,quantidade,preco_unitario,custo_unitario,desconto_pct,status_pedido,publico,tamanho,data_entrega
0,844,2025-11-21 18:02:35,Fantasia de vampiro,Fantasia,Loja física,Curitiba,3,132.5,72.08,15,Cancelado,Adulto,G,NaN
1,378,2024-10-29 18:41:26,Fantasia de bruxa,FANTASIA!!!,Loja física,Maringá,3,110.0,57.00,5,Concluído,Adulto,M,2024-11-03 18:41:26
2,953,2025-09-05 21:16:09,Fantasia de bruxa,Fantasia,Web,Maringá,2,116.6,60.42,5,Concluído,Adulto,M,2025-09-10 21:16:09

In [4]:
vendas.shape

(1500, 14)

In [5]:
vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pedido_id       1500 non-null   int64
 1   data_venda      1500 non-null   str
 2   produto         1500 non-null   str
 3   categoria       1482 non-null   str
 4   canal_venda     1500 non-null   str
 5   cidade          1500 non-null   str
 6   quantidade      1500 non-null   int64
 7   preco_unitario  1488 non-null   float64
 8   custo_unitario  1493 non-null   float64
 9   desconto_pct    1500 non-null   int64
 10  status_pedido   1500 non-null   str
 11  publico         1500 non-null   str
 12  tamanho         1500 non-null   str
 13  data_entrega    1357 non-null   str
dtypes: float64(2), int64(3), str(9)
memory usage: 164.2 KB

### Verificando os valores únicos das colunas

In [6]:
# Verificando os valores presentes na coluna produto
# Para identificar nomes diferentes para o mesmo produto

vendas["produto"].value_counts()

produto
Fantasia de vampiro     272
Chapeu de bruxa         272
Fantasia de bruxa       255
Fantasia de abobora     240
Mascara assustadora     237
Fantasia de fantasma    224
Name: count, dtype: int64

In [7]:
# Verificando os valores presentes na coluna categoria 
# Para identificar nomes diferentes para a mesma categoria

# Para esta coluna precisaremos realizar um tratamento nos valores 
# pois as categorias fantasia e acessorio foram escritas de diversas maneiras

vendas["categoria"].value_counts()

categoria
Fantasia            892
Acessorio           459
 Fantasia            48
  FANTASIA!!!        39
 Acessorio           28
  ACESSORIO!!!       16
Name: count, dtype: int64

In [8]:
# Verificando os valores presentes na coluna canal_venda
# Para identificar nomes diferentes para o mesmo canal de venda

# Para esta coluna precisaremos realizar um tratamento nos valores 
# pois os canais de venda estão com nomes divergentes dos canais padrão

vendas["canal_venda"].value_counts()

canal_venda
Web              646
Loja física      535
Mercado          274
 web              20
 loja física      16
 mercado           9
Name: count, dtype: int64

In [9]:
# Verificando os valores presentes na coluna cidade
# Para identificar nomes diferentes para a mesma cidade

vendas["cidade"].value_counts()

cidade
Londrina    396
Cascavel    378
Maringá     375
Curitiba    351
Name: count, dtype: int64

In [10]:
# Verificando os valores presentes na coluna status_pedido
# Para identificar nomes diferentes para o mesmo status de pedido

vendas["status_pedido"].value_counts()

status_pedido
Concluído    1345
Cancelado     109
Devolvido      46
Name: count, dtype: int64

In [11]:
# Verificando os valores presentes na coluna publico
# Para identificar nomes diferentes para o mesmo tipo de público

vendas["publico"].value_counts()

publico
Adulto      527
Todos       509
Infantil    464
Name: count, dtype: int64

In [12]:
# Verificando os valores presentes na coluna tamanho
# Para identificar nomes diferentes para o mesmo tamanho de produto

vendas["tamanho"].value_counts()

tamanho
Unico    509
M        479
G        272
P        240
Name: count, dtype: int64

Precisaremos tratar os valores das colunas "categoria" e "canal_venda"

In [13]:
# Verificar quais colunas possuem valores NaN

vendas.isna().sum()

pedido_id           0
data_venda          0
produto             0
categoria          18
canal_venda         0
cidade              0
quantidade          0
preco_unitario     12
custo_unitario      7
desconto_pct        0
status_pedido       0
publico             0
tamanho             0
data_entrega      143
dtype: int64

Em 4 colunas temos linhas com valores nulos, teremos que analisar o contexto de cada informação ausente e verificar a necessidade de tratamento

In [14]:
data_entrega_nan = vendas.loc[vendas["data_entrega"].isna() == True]

In [15]:
data_entrega_nan.head()

,pedido_id,data_venda,produto,categoria,canal_venda,cidade,quantidade,preco_unitario,custo_unitario,desconto_pct,status_pedido,publico,tamanho,data_entrega
0,844,2025-11-21 18:02:35,Fantasia de vampiro,Fantasia,Loja física,Curitiba,3,132.5,72.08,15,Cancelado,Adulto,G,NaN
8,186,2024-08-17 22:17:18,Fantasia de fantasma,Fantasia,Web,Londrina,2,75.0,39.00,0,Cancelado,Infantil,M,NaN
21,662,2024-10-21 19:27:01,Fantasia de vampiro,Fantasia,Web,Londrina,2,125.0,68.00,0,Cancelado,Adulto,G,NaN
49,1170,2025-08-19 22:20:19,Fantasia de abobora,Fantasia,Web,Maringá,2,90.1,46.64,0,Concluído,Infantil,P,NaN
59,896,2025-09-25 21:51:50,Fantasia de fantasma,Fantasia,Web,Maringá,2,79.5,41.34,0,Cancelado,Infantil,M,NaN

In [16]:
data_entrega_nan["status_pedido"].value_counts()

status_pedido
Cancelado    109
Concluído     34
Name: count, dtype: int64

In [17]:
data_entrega_nan.loc[data_entrega_nan["status_pedido"] == "Concluído"]

,pedido_id,data_venda,produto,categoria,canal_venda,cidade,quantidade,preco_unitario,custo_unitario,desconto_pct,status_pedido,publico,tamanho,data_entrega
49,1170,2025-08-19 22:20:19,Fantasia de abobora,Fantasia,Web,Maringá,2,90.10,46.64,0,Concluído,Infantil,P,NaN
117,990,2025-10-13 20:00:16,Fantasia de fantasma,Fantasia,web,Londrina,2,79.50,41.34,0,Concluído,Infantil,M,NaN
152,740,data_invalida,Fantasia de abobora,Fantasia,Web,Curitiba,2,85.00,44.00,25,Concluído,Infantil,P,NaN
164,630,2024-11-03 12:14:23,Chapeu de bruxa,Acessorio,Mercado,Londrina,-1,22.00,8.00,10,Concluído,Todos,Unico,NaN
226,45,2024-11-15 12:17:08,Mascara assustadora,Acessorio,Mercado,Maringá,4,35.00,12.00,15,Concluído,Todos,Unico,NaN
240,720,2024-08-05 21:36:11,Fantasia de fantasma,NaN,Web,Cascavel,2,75.00,39.00,0,Concluído,Infantil,M,NaN
255,370,data_invalida,Fantasia de vampiro,Fantasia,Web,Curitiba,1,125.00,68.00,0,Concluído,Adulto,G,NaN
301,270,2024-10-27 09:44:47,Fantasia de abobora,FANTASIA!!!,Mercado,Curitiba,5,85.00,44.00,0,Concluído,Infantil,P,NaN
320,810,2025-10-25 19:29:32,Fantasia de vampiro,FANTASIA!!!,Web,Curitiba,3,132.50,72.08,0,Concluído,Adulto,G,NaN
341,945,2025-10-27 18:18:33,Fantasia de bruxa,FANTASIA!!!,Web,Londrina,3,116.60,60.42,0,Concluído,Adulto,M,NaN
357,675,2024-10-15 11:07:27,Mascara assustadora,ACESSORIO!!!,Loja física,Londrina,3,35.00,12.00,0,Concluído,Todos,Unico,NaN
380,135,2024-10-22 18:44:20,Fantasia de vampiro,FANTASIA!!!,Web,Londrina,1,125.00,68.00,0,Concluído,Adulto,G,NaN
413,315,2024-10-12 18:09:59,Mascara assustadora,Acessorio,Mercado,Maringá,3,35.00,12.00,0,Concluído,Todos,Unico,NaN
447,360,2024-10-27 15:54:17,Chapeu de bruxa,Acessorio,Loja física,Cascavel,2,22.00,8.00,10,Concluído,Todos,Unico,NaN
530,1485,2025-08-31 19:38:12,Fantasia de abobora,FANTASIA!!!,web,Maringá,1,90.10,46.64,0,Concluído,Infantil,P,NaN
581,540,2024-10-02 21:09:13,Fantasia de vampiro,FANTASIA!!!,Web,Maringá,3,125.00,68.00,5,Concluído,Adulto,G,NaN
602,1350,2025-09-23 16:24:37,Fantasia de vampiro,FANTASIA!!!,Loja física,Curitiba,1,132.50,72.08,10,Concluído,Adulto,G,NaN
714,1480,data_invalida,Fantasia de vampiro,Fantasia,Web,Cascavel,2,132.50,72.08,0,Concluído,Adulto,G,NaN
723,1305,2025-10-02 11:24:13,Chapeu de bruxa,Acessorio,Mercado,Curitiba,4,23.32,8.48,0,Concluído,Todos,Unico,NaN
809,450,2024-09-16 19:33:38,Fantasia de bruxa,Fantasia,Web,Cascavel,1,110.00,57.00,5,Concluído,Adulto,M,NaN
840,855,2025-10-03 18:06:38,Chapeu de bruxa,Acessorio,Web,Cascavel,1,23.32,8.48,0,Concluído,Todos,Unico,NaN
862,495,2024-10-15 19:35:05,Fantasia de abobora,Fantasia,web,Cascavel,2,85.00,44.00,5,Concluído,Infantil,P,NaN
884,1110,data_invalida,Fantasia de bruxa,Fantasia,Web,Cascavel,1,116.60,60.42,0,Concluído,Adulto,M,NaN
932,1395,2025-08-03 19:57:36,Fantasia de vampiro,Fantasia,Web,Curitiba,1,132.50,72.08,0,Concluído,Adulto,G,NaN
1107,585,2024-08-17 11:04:38,Fantasia de vampiro,Fantasia,Loja física,Curitiba,3,125.00,68.00,5,Concluído,Adulto,G,NaN
1168,90,2024-09-24 20:14:04,Fantasia de bruxa,Fantasia,Web,Londrina,2,110.00,57.00,5,Concluído,Adulto,M,NaN
1200,900,2025-10-18 19:55:27,Chapeu de bruxa,Acessorio,Mercado,Londrina,4,23.32,8.48,0,Concluído,Todos,Unico,NaN
1210,1035,2025-10-09 18:07:09,Chapeu de bruxa,Acessorio,Loja física,Maringá,1,23.32,8.48,0,Concluído,Todos,Unico,NaN
1251,225,2024-09-16 17:12:35,Fantasia de bruxa,Fantasia,Loja física,Londrina,1,110.00,57.00,0,Concluído,Adulto,M,NaN
1265,180,2024-11-06 16:50:03,Fantasia de abobora,Fantasia,Loja física,Curitiba,1,85.00,44.00,20,Concluído,Infantil,P,NaN
1312,1125,2025-10-23 12:38:12,Fantasia de bruxa,Fantasia,Loja física,Cascavel,1,NaN,60.42,5,Concluído,Adulto,M,NaN
1332,1215,2025-11-21 21:23:17,Fantasia de abobora,FANTASIA!!!,Web,Curitiba,1,90.10,46.64,10,Concluído,Infantil,P,NaN
1421,765,2025-10-03 21:47:16,Fantasia de vampiro,Fantasia,Web,Curitiba,2,132.50,72.08,0,Concluído,Adulto,G,NaN
1448,1260,2025-10-06 11:49:25,Chapeu de bruxa,Acessorio,Loja física,Maringá,-1,23.32,8.48,0,Concluído,Todos,Unico,NaN

Nas informações acima podemos observar que existem 34 registros sem data de entrega, porém com status do pedido concluído. Então fica descartada a hipótese de que a falta de dados na coluna data_entrega é consequência somente de pedidos que não foi realizado a entrega, pois existem registros de produtos que foram entregues porém sem o registro da data.

Uma segunda hipótese para justificar registros com status concluído porém sem data de entrega, seria que os registros estavam duplicados e a data de entrega foi gravada em apenas uma das linhas duplicadas

In [18]:
# Verificando se há linhas duplicadas no dataset original 
# 

print(f"Quantidade de linhas duplicadas no dataset: {vendas.duplicated().sum()}")

Quantidade de linhas duplicadas no dataset: 0

In [19]:
# Verificando se há mais de uma linha com o mesmo pedido_id

print(f"Número de registros com o id repetido: {vendas.duplicated(subset=["pedido_id"]).sum()}")

Número de registros com o id repetido: 0

In [20]:
print(f"Número de registros com id único: {vendas["pedido_id"].nunique()}")

Número de registros com id único: 1500

Após a análise das informações acima podemos descartar a segunda hipótese também, pois nos dados não há registros com pedido_id duplicados

INICIO TRATAMENTO DO DATASET

In [21]:
vendas_tratado = vendas.copy()

In [22]:
vendas_tratado.shape

(1500, 14)

Tratamento de strings

In [23]:
# Criação da função normalizar_string
# .strip - remove os espaços
# .lower - deixa as letras em minúsculo
# replace r"[^\w\s]" - mantém apenas os caracteres alfanuméricos e espaços

def normalizar_string(texto : str) -> str:
    """ 
    Função para remover espaços desnecessários, deixar todas as letras minúsculas e remover pontuações de uma string 
    """
    
    texto = texto.str.strip().str.lower().str.replace(r"[^\w\s]", "", regex=True)
    return texto

In [24]:
# Aplicando a função normalizar_string para formatar os valores da coluna categoria

vendas_tratado["categoria"] = normalizar_string(vendas_tratado["categoria"])

In [25]:
vendas_tratado["categoria"].value_counts()

categoria
fantasia     979
acessorio    503
Name: count, dtype: int64

In [26]:
# Formatando os valores da coluna canal_venda
# .strip() remove os espaços
# .capitalize() deixa a primeira letra maiúscula

vendas_tratado["canal_venda"] = vendas_tratado["canal_venda"].str.strip().str.capitalize()

In [27]:
vendas_tratado["canal_venda"].value_counts()

canal_venda
Web            666
Loja física    551
Mercado        283
Name: count, dtype: int64

Tratamento de datas

In [28]:
# Primeiro renomeamos a coluna original para manter a identificação

vendas_tratado = vendas_tratado.rename(columns={"data_venda" : "data_venda_original"})

In [29]:
# Criaremos uma nova coluna para armazenar as datas no formato datetime

vendas_tratado["data_venda_tratado"] = pd.to_datetime(vendas_tratado["data_venda_original"], format="%Y-%m-%d %H:%M:%S", errors="coerce")

In [30]:
# Verificamos se a nova coluna criada ficou no formato correto

vendas_tratado.dtypes

pedido_id                       int64
data_venda_original               str
produto                           str
categoria                         str
canal_venda                       str
cidade                            str
quantidade                      int64
preco_unitario                float64
custo_unitario                float64
desconto_pct                    int64
status_pedido                     str
publico                           str
tamanho                           str
data_entrega                      str
data_venda_tratado     datetime64[us]
dtype: object

In [31]:
# Agora conforme pedido criaremos uma coluna para representação da data no formato brasileiro

vendas_tratado["data_venda"] = vendas_tratado["data_venda_tratado"].dt.strftime("%d/%m/%Y")

Tratamento de valores nulos

In [32]:
vendas_tratado["categoria"] = vendas_tratado["categoria"].fillna("sem categoria")

In [84]:
qtd_vazias = vendas_tratado["categoria"].loc[vendas_tratado["categoria"] == "sem categoria"].count()
qtd_alteradas = vendas["categoria"].loc[(vendas["categoria"] != "Fantasia") & (vendas["categoria"] != "Acessorio")].count()

print(f"Quantidade de categorias vazias preenchidas: {qtd_vazias}")
print(f"Quantidade de categorias não vazias alteradas: {qtd_alteradas}")

Quantidade de categorias vazias preenchidas: 18
Quantidade de categorias não vazias alteradas: 131

In [33]:
vendas_tratado.isna().sum()

pedido_id                0
data_venda_original      0
produto                  0
categoria                0
canal_venda              0
cidade                   0
quantidade               0
preco_unitario          12
custo_unitario           7
desconto_pct             0
status_pedido            0
publico                  0
tamanho                  0
data_entrega           143
data_venda_tratado       4
data_venda               4
dtype: int64

In [34]:
vendas_tratado.head(10)

,pedido_id,data_venda_original,produto,categoria,canal_venda,cidade,quantidade,preco_unitario,custo_unitario,desconto_pct,status_pedido,publico,tamanho,data_entrega,data_venda_tratado,data_venda
0,844,2025-11-21 18:02:35,Fantasia de vampiro,fantasia,Loja física,Curitiba,3,132.5,72.08,15,Cancelado,Adulto,G,NaN,2025-11-21 18:02:35,21/11/2025
1,378,2024-10-29 18:41:26,Fantasia de bruxa,fantasia,Loja física,Maringá,3,110.0,57.00,5,Concluído,Adulto,M,2024-11-03 18:41:26,2024-10-29 18:41:26,29/10/2024
2,953,2025-09-05 21:16:09,Fantasia de bruxa,fantasia,Web,Maringá,2,116.6,60.42,5,Concluído,Adulto,M,2025-09-10 21:16:09,2025-09-05 21:16:09,05/09/2025
3,11,2024-11-08 11:29:44,Mascara assustadora,acessorio,Loja física,Cascavel,1,35.0,12.00,15,Concluído,Todos,Unico,2024-11-11 11:29:44,2024-11-08 11:29:44,08/11/2024
4,1335,2025-08-23 11:22:05,Mascara assustadora,acessorio,Mercado,Curitiba,3,37.1,12.72,0,Concluído,Todos,Unico,2025-08-25 11:22:05,2025-08-23 11:22:05,23/08/2025
5,359,2024-10-01 15:00:11,Fantasia de fantasma,fantasia,Loja física,Curitiba,2,75.0,39.00,10,Concluído,Infantil,M,2024-10-07 15:00:11,2024-10-01 15:00:11,01/10/2024
6,1066,2025-08-26 19:49:13,Fantasia de vampiro,fantasia,Web,Maringá,3,132.5,72.08,5,Devolvido,Adulto,G,2025-08-29 19:49:13,2025-08-26 19:49:13,26/08/2025
7,556,2024-10-12 14:13:18,Mascara assustadora,acessorio,Loja física,Curitiba,2,35.0,12.00,0,Concluído,Todos,Unico,2024-10-15 14:13:18,2024-10-12 14:13:18,12/10/2024
8,186,2024-08-17 22:17:18,Fantasia de fantasma,fantasia,Web,Londrina,2,75.0,39.00,0,Cancelado,Infantil,M,NaN,2024-08-17 22:17:18,17/08/2024
9,823,2025-10-11 19:01:38,Fantasia de fantasma,fantasia,Loja física,Londrina,2,79.5,41.34,10,Concluído,Infantil,M,2025-10-16 19:01:38,2025-10-11 19:01:38,11/10/2025

Agora iremos verificar as colunas de valores numéricos que podem possuir valores inválidos

In [88]:
qtd_invalidos = vendas_tratado["quantidade"].loc[vendas_tratado["quantidade"] <= 0].count()

print(f"A coluna 'quantidade' possui {qtd_invalidos} registros menores ou iguais a 0")

A coluna 'quantidade' possui 7 registros menores ou iguais a 0

In [145]:
((vendas_tratado["preco_unitario"] < 0) | (vendas_tratado["preco_unitario"].isna())).sum()

np.int64(12)

In [111]:
preco_unit_invalid = vendas_tratado["preco_unitario"].loc[vendas_tratado["preco_unitario"] < 0].count()
preco_unit_nan = vendas_tratado["preco_unitario"].isna().sum()

print("Dados da coluna 'preco_unitario'")
print(f"\nPossui {preco_unit_invalid} valores inválidos (menores que zero)")
print(f"Possui {preco_unit_nan} valores ausentes")
print(f"Totalizando {preco_unit_invalid + preco_unit_nan} problemas")

Dados da coluna 'preco_unitario'

Possui 0 valores inválidos (menores que zero)
Possui 12 valores ausentes
Totalizando 12 problemas

In [ ]:
intersec = vendas_tratado["pedido_id"].loc[(vendas_tratado["quantidade"] <= 0) & (vendas_tratado["preco_unitario"].isna())].count()

np.int64(0)

In [ ]:
tot

In [ ]:
quantidade_invalida = vendas_tratado[vendas_tratado["quantidade"] <= 0]

quantidade_invalida

,pedido_id,data_venda_original,produto,categoria,canal_venda,cidade,quantidade,preco_unitario,custo_unitario,desconto_pct,status_pedido,publico,tamanho,data_entrega,data_venda_tratado,data_venda
164,630,2024-11-03 12:14:23,Chapeu de bruxa,acessorio,Mercado,Londrina,-1,22.00,8.00,10,Concluído,Todos,Unico,NaN,2024-11-03 12:14:23,03/11/2024
672,840,2025-11-05 16:16:55,Chapeu de bruxa,acessorio,Mercado,Maringá,-1,23.32,8.48,10,Concluído,Todos,Unico,2025-11-07 16:16:55,2025-11-05 16:16:55,05/11/2025
845,420,2024-10-30 18:48:52,Mascara assustadora,acessorio,Mercado,Curitiba,-1,35.00,12.00,10,Concluído,Todos,Unico,2024-11-01 18:48:52,2024-10-30 18:48:52,30/10/2024
1126,210,2024-11-06 11:44:46,Fantasia de vampiro,fantasia,Loja física,Curitiba,-1,125.00,68.00,25,Concluído,Adulto,G,2024-11-08 11:44:46,2024-11-06 11:44:46,06/11/2024
1260,1050,2025-10-23 20:33:54,Fantasia de abobora,fantasia,Web,Maringá,-1,90.10,46.64,5,Concluído,Infantil,P,2025-10-25 20:33:54,2025-10-23 20:33:54,23/10/2025
1448,1260,2025-10-06 11:49:25,Chapeu de bruxa,acessorio,Loja física,Maringá,-1,23.32,8.48,0,Concluído,Todos,Unico,NaN,2025-10-06 11:49:25,06/10/2025
1481,1470,2025-10-12 19:01:44,Fantasia de vampiro,fantasia,Web,Curitiba,-1,132.50,72.08,5,Concluído,Adulto,G,2025-10-14 19:01:44,2025-10-12 19:01:44,12/10/2025

In [48]:
vendas_tratado.loc[vendas_tratado["custo_unitario"].isna()]

,pedido_id,data_venda_original,produto,categoria,canal_venda,cidade,quantidade,preco_unitario,custo_unitario,desconto_pct,status_pedido,publico,tamanho,data_entrega,data_venda_tratado,data_venda
346,760,2025-11-12 19:27:12,Fantasia de vampiro,fantasia,Web,Maringá,2,132.5,NaN,15,Concluído,Adulto,G,2025-11-14 19:27:12,2025-11-12 19:27:12,12/11/2025
501,380,2024-10-09 20:40:03,Fantasia de fantasma,fantasia,Web,Curitiba,2,75.0,NaN,5,Concluído,Infantil,M,2024-10-11 20:40:03,2024-10-09 20:40:03,09/10/2024
926,1330,2025-11-16 19:44:19,Mascara assustadora,acessorio,Web,Maringá,3,37.1,NaN,20,Concluído,Todos,Unico,2025-11-18 19:44:19,2025-11-16 19:44:19,16/11/2025
1131,950,2025-09-16 22:45:41,Fantasia de vampiro,fantasia,Web,Curitiba,2,132.5,NaN,10,Devolvido,Adulto,G,2025-09-18 22:45:41,2025-09-16 22:45:41,16/09/2025
1217,190,2024-10-15 19:59:52,Fantasia de abobora,fantasia,Web,Maringá,1,85.0,NaN,5,Concluído,Infantil,P,2024-10-17 19:59:52,2024-10-15 19:59:52,15/10/2024
1248,1140,2025-11-15 10:44:59,Fantasia de vampiro,fantasia,Loja física,Cascavel,3,132.5,NaN,0,Concluído,Adulto,G,2025-11-17 10:44:59,2025-11-15 10:44:59,15/11/2025
1456,570,2024-10-18 11:46:36,Chapeu de bruxa,acessorio,Loja física,Maringá,2,22.0,NaN,0,Concluído,Todos,Unico,2024-10-20 11:46:36,2024-10-18 11:46:36,18/10/2024

In [46]:
preco_unit_invalido = vendas_tratado[vendas_tratado["preco_unitario"].isna()]

preco_unit_invalido

,pedido_id,data_venda_original,produto,categoria,canal_venda,cidade,quantidade,preco_unitario,custo_unitario,desconto_pct,status_pedido,publico,tamanho,data_entrega,data_venda_tratado,data_venda
23,1500,2025-11-04 16:44:22,Chapeu de bruxa,acessorio,Loja física,Curitiba,3,NaN,8.48,0,Concluído,Todos,Unico,2025-11-06 16:44:22,2025-11-04 16:44:22,04/11/2025
199,625,2024-08-25 22:22:42,Fantasia de fantasma,fantasia,Web,Curitiba,2,NaN,39.00,10,Concluído,Infantil,M,2024-08-27 22:22:42,2024-08-25 22:22:42,25/08/2024
216,1000,2025-09-18 19:48:22,Fantasia de abobora,fantasia,Web,Curitiba,1,NaN,46.64,10,Concluído,Infantil,P,2025-09-20 19:48:22,2025-09-18 19:48:22,18/09/2025
239,1250,2025-10-07 19:21:37,Fantasia de bruxa,fantasia,Web,Curitiba,1,NaN,60.42,0,Concluído,Adulto,M,2025-10-09 19:21:37,2025-10-07 19:21:37,07/10/2025
293,500,2024-10-09 18:26:36,Fantasia de abobora,fantasia,Loja física,Maringá,1,NaN,44.00,10,Concluído,Infantil,P,2024-10-11 18:26:36,2024-10-09 18:26:36,09/10/2024
503,375,2024-08-28 18:59:14,Fantasia de vampiro,fantasia,Web,Maringá,3,NaN,68.00,0,Concluído,Adulto,G,2024-08-30 18:59:14,2024-08-28 18:59:14,28/08/2024
571,250,2024-10-17 09:43:43,Mascara assustadora,acessorio,Mercado,Cascavel,4,NaN,12.00,0,Concluído,Todos,Unico,2024-10-19 09:43:43,2024-10-17 09:43:43,17/10/2024
583,125,2024-10-31 13:59:44,Chapeu de bruxa,acessorio,Loja física,Cascavel,1,NaN,8.00,5,Concluído,Todos,Unico,2024-11-02 13:59:44,2024-10-31 13:59:44,31/10/2024
1066,875,2025-11-03 19:41:04,Chapeu de bruxa,acessorio,Mercado,Curitiba,6,NaN,8.48,10,Cancelado,Todos,Unico,NaN,2025-11-03 19:41:04,03/11/2025
1092,750,2024-10-28 09:26:11,Fantasia de abobora,fantasia,Loja física,Curitiba,2,NaN,44.00,0,Concluído,Infantil,P,2024-10-30 09:26:11,2024-10-28 09:26:11,28/10/2024
1275,1375,2025-09-18 15:15:55,Fantasia de vampiro,fantasia,Loja física,Londrina,2,NaN,72.08,0,Concluído,Adulto,G,2025-09-20 15:15:55,2025-09-18 15:15:55,18/09/2025
1312,1125,2025-10-23 12:38:12,Fantasia de bruxa,fantasia,Loja física,Cascavel,1,NaN,60.42,5,Concluído,Adulto,M,NaN,2025-10-23 12:38:12,23/10/2025

In [ ]:
vendas_tratado["invalido"]

In [ ]:
def validar_linha(linha):
    """ Função para validar as linhas de um dataframe.
        Retorna 1 se a linha for INVÁLIDA e 0 se for VÁLIDA.
    """
    # Quantidade deve ser maior que 0
    if linha["quantidade"] <= 0:
        return 1
        
    # Preço unitário não pode ser nulo e nem ser negativo
    elif pd.isna(linha["preco_unitario"]) or linha["preco_unitario"] < 0:
        return 1
        
    # Custo unitário não pode ser nulo
    elif pd.isna(linha["custo_unitario"]):
        return 1
        
    # Pedido sem data de entrega porém com status Concluído
    elif pd.isna(linha["data_entrega"]) and linha["status_pedido"] == "Concluído":
        return 1
        
    else: 
        return 0

In [65]:
vendas_tratado["invalido"] = vendas_tratado.apply(validar_linha, axis=1)

In [71]:
vendas_tratado.loc[vendas_tratado["invalido"] == 1]

,pedido_id,data_venda_original,produto,categoria,canal_venda,cidade,quantidade,preco_unitario,custo_unitario,desconto_pct,status_pedido,publico,tamanho,data_entrega,data_venda_tratado,data_venda,invalido
49,1170,2025-08-19 22:20:19,Fantasia de abobora,fantasia,Web,Maringá,2,90.10,46.64,0,Concluído,Infantil,P,NaN,2025-08-19 22:20:19,19/08/2025,1
117,990,2025-10-13 20:00:16,Fantasia de fantasma,fantasia,Web,Londrina,2,79.50,41.34,0,Concluído,Infantil,M,NaN,2025-10-13 20:00:16,13/10/2025,1
152,740,data_invalida,Fantasia de abobora,fantasia,Web,Curitiba,2,85.00,44.00,25,Concluído,Infantil,P,NaN,NaT,NaN,1
164,630,2024-11-03 12:14:23,Chapeu de bruxa,acessorio,Mercado,Londrina,-1,22.00,8.00,10,Concluído,Todos,Unico,NaN,2024-11-03 12:14:23,03/11/2024,1
226,45,2024-11-15 12:17:08,Mascara assustadora,acessorio,Mercado,Maringá,4,35.00,12.00,15,Concluído,Todos,Unico,NaN,2024-11-15 12:17:08,15/11/2024,1
240,720,2024-08-05 21:36:11,Fantasia de fantasma,sem categoria,Web,Cascavel,2,75.00,39.00,0,Concluído,Infantil,M,NaN,2024-08-05 21:36:11,05/08/2024,1
255,370,data_invalida,Fantasia de vampiro,fantasia,Web,Curitiba,1,125.00,68.00,0,Concluído,Adulto,G,NaN,NaT,NaN,1
301,270,2024-10-27 09:44:47,Fantasia de abobora,fantasia,Mercado,Curitiba,5,85.00,44.00,0,Concluído,Infantil,P,NaN,2024-10-27 09:44:47,27/10/2024,1
320,810,2025-10-25 19:29:32,Fantasia de vampiro,fantasia,Web,Curitiba,3,132.50,72.08,0,Concluído,Adulto,G,NaN,2025-10-25 19:29:32,25/10/2025,1
341,945,2025-10-27 18:18:33,Fantasia de bruxa,fantasia,Web,Londrina,3,116.60,60.42,0,Concluído,Adulto,M,NaN,2025-10-27 18:18:33,27/10/2025,1
346,760,2025-11-12 19:27:12,Fantasia de vampiro,fantasia,Web,Maringá,2,132.50,NaN,15,Concluído,Adulto,G,2025-11-14 19:27:12,2025-11-12 19:27:12,12/11/2025,1
357,675,2024-10-15 11:07:27,Mascara assustadora,acessorio,Loja física,Londrina,3,35.00,12.00,0,Concluído,Todos,Unico,NaN,2024-10-15 11:07:27,15/10/2024,1
380,135,2024-10-22 18:44:20,Fantasia de vampiro,fantasia,Web,Londrina,1,125.00,68.00,0,Concluído,Adulto,G,NaN,2024-10-22 18:44:20,22/10/2024,1
413,315,2024-10-12 18:09:59,Mascara assustadora,acessorio,Mercado,Maringá,3,35.00,12.00,0,Concluído,Todos,Unico,NaN,2024-10-12 18:09:59,12/10/2024,1
447,360,2024-10-27 15:54:17,Chapeu de bruxa,acessorio,Loja física,Cascavel,2,22.00,8.00,10,Concluído,Todos,Unico,NaN,2024-10-27 15:54:17,27/10/2024,1
501,380,2024-10-09 20:40:03,Fantasia de fantasma,fantasia,Web,Curitiba,2,75.00,NaN,5,Concluído,Infantil,M,2024-10-11 20:40:03,2024-10-09 20:40:03,09/10/2024,1
530,1485,2025-08-31 19:38:12,Fantasia de abobora,fantasia,Web,Maringá,1,90.10,46.64,0,Concluído,Infantil,P,NaN,2025-08-31 19:38:12,31/08/2025,1
581,540,2024-10-02 21:09:13,Fantasia de vampiro,fantasia,Web,Maringá,3,125.00,68.00,5,Concluído,Adulto,G,NaN,2024-10-02 21:09:13,02/10/2024,1
602,1350,2025-09-23 16:24:37,Fantasia de vampiro,fantasia,Loja física,Curitiba,1,132.50,72.08,10,Concluído,Adulto,G,NaN,2025-09-23 16:24:37,23/09/2025,1
672,840,2025-11-05 16:16:55,Chapeu de bruxa,acessorio,Mercado,Maringá,-1,23.32,8.48,10,Concluído,Todos,Unico,2025-11-07 16:16:55,2025-11-05 16:16:55,05/11/2025,1
714,1480,data_invalida,Fantasia de vampiro,fantasia,Web,Cascavel,2,132.50,72.08,0,Concluído,Adulto,G,NaN,NaT,NaN,1
723,1305,2025-10-02 11:24:13,Chapeu de bruxa,acessorio,Mercado,Curitiba,4,23.32,8.48,0,Concluído,Todos,Unico,NaN,2025-10-02 11:24:13,02/10/2025,1
809,450,2024-09-16 19:33:38,Fantasia de bruxa,fantasia,Web,Cascavel,1,110.00,57.00,5,Concluído,Adulto,M,NaN,2024-09-16 19:33:38,16/09/2024,1
840,855,2025-10-03 18:06:38,Chapeu de bruxa,acessorio,Web,Cascavel,1,23.32,8.48,0,Concluído,Todos,Unico,NaN,2025-10-03 18:06:38,03/10/2025,1
845,420,2024-10-30 18:48:52,Mascara assustadora,acessorio,Mercado,Curitiba,-1,35.00,12.00,10,Concluído,Todos,Unico,2024-11-01 18:48:52,2024-10-30 18:48:52,30/10/2024,1
862,495,2024-10-15 19:35:05,Fantasia de abobora,fantasia,Web,Cascavel,2,85.00,44.00,5,Concluído,Infantil,P,NaN,2024-10-15 19:35:05,15/10/2024,1
884,1110,data_invalida,Fantasia de bruxa,fantasia,Web,Cascavel,1,116.60,60.42,0,Concluído,Adulto,M,NaN,NaT,NaN,1
926,1330,2025-11-16 19:44:19,Mascara assustadora,acessorio,Web,Maringá,3,37.10,NaN,20,Concluído,Todos,Unico,2025-11-18 19:44:19,2025-11-16 19:44:19,16/11/2025,1
932,1395,2025-08-03 19:57:36,Fantasia de vampiro,fantasia,Web,Curitiba,1,132.50,72.08,0,Concluído,Adulto,G,NaN,2025-08-03 19:57:36,03/08/2025,1
1107,585,2024-08-17 11:04:38,Fantasia de vampiro,fantasia,Loja física,Curitiba,3,125.00,68.00,5,Concluído,Adulto,G,NaN,2024-08-17 11:04:38,17/08/2024,1
1126,210,2024-11-06 11:44:46,Fantasia de vampiro,fantasia,Loja física,Curitiba,-1,125.00,68.00,25,Concluído,Adulto,G,2024-11-08 11:44:46,2024-11-06 11:44:46,06/11/2024,1
1131,950,2025-09-16 22:45:41,Fantasia de vampiro,fantasia,Web,Curitiba,2,132.50,NaN,10,Devolvido,Adulto,G,2025-09-18 22:45:41,2025-09-16 22:45:41,16/09/2025,1
1168,90,2024-09-24 20:14:04,Fantasia de bruxa,fantasia,Web,Londrina,2,110.00,57.00,5,Concluído,Adulto,M,NaN,2024-09-24 20:14:04,24/09/2024,1
1200,900,2025-10-18 19:55:27,Chapeu de bruxa,acessorio,Mercado,Londrina,4,23.32,8.48,0,Concluído,Todos,Unico,NaN,2025-10-18 19:55:27,18/10/2025,1
1210,1035,2025-10-09 18:07:09,Chapeu de bruxa,acessorio,Loja física,Maringá,1,23.32,8.48,0,Concluído,Todos,Unico,NaN,2025-10-09 18:07:09,09/10/2025,1
1217,190,2024-10-15 19:59:52,Fantasia de abobora,fantasia,Web,Maringá,1,85.00,NaN,5,Concluído,Infantil,P,2024-10-17 19:59:52,2024-10-15 19:59:52,15/10/2024,1
1248,1140,2025-11-15 10:44:59,Fantasia de vampiro,fantasia,Loja física,Cascavel,3,132.50,NaN,0,Concluído,Adulto,G,2025-11-17 10:44:59,2025-11-15 10:44:59,15/11/2025,1
1251,225,2024-09-16 17:12:35,Fantasia de bruxa,fantasia,Loja física,Londrina,1,110.00,57.00,0,Concluído,Adulto,M,NaN,2024-09-16 17:12:35,16/09/2024,1
1260,1050,2025-10-23 20:33:54,Fantasia de abobora,fantasia,Web,Maringá,-1,90.10,46.64,5,Concluído,Infantil,P,2025-10-25 20:33:54,2025-10-23 20:33:54,23/10/2025,1
1265,180,2024-11-06 16:50:03,Fantasia de abobora,fantasia,Loja física,Curitiba,1,85.00,44.00,20,Concluído,Infantil,P,NaN,2024-11-06 16:50:03,06/11/2024,1
1312,1125,2025-10-23 12:38:12,Fantasia de bruxa,fantasia,Loja física,Cascavel,1,NaN,60.42,5,Concluído,Adulto,M,NaN,2025-10-23 12:38:12,23/10/2025,1
1332,1215,2025-11-21 21:23:17,Fantasia de abobora,fantasia,Web,Curitiba,1,90.10,46.64,10,Concluído,Infantil,P,NaN,2025-11-21 21:23:17,21/11/2025,1
1421,765,2025-10-03 21:47:16,Fantasia de vampiro,fantasia,Web,Curitiba,2,132.50,72.08,0,Concluído,Adulto,G,NaN,2025-10-03 21:47:16,03/10/2025,1
1448,1260,2025-10-06 11:49:25,Chapeu de bruxa,acessorio,Loja física,Maringá,-1,23.32,8.48,0,Concluído,Todos,Unico,NaN,2025-10-06 11:49:25,06/10/2025,1
1456,570,2024-10-18 11:46:36,Chapeu de bruxa,acessorio,Loja física,Maringá,2,22.00,NaN,0,Concluído,Todos,Unico,2024-10-20 11:46:36,2024-10-18 11:46:36,18/10/2024,1
1481,1470,2025-10-12 19:01:44,Fantasia de vampiro,fantasia,Web,Curitiba,-1,132.50,72.08,5,Concluído,Adulto,G,2025-10-14 19:01:44,2025-10-12 19:01:44,12/10/2025,1

In [72]:
vendas_tratado["invalido"].sum()

np.int64(46)